# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-28 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alternative',
            name='text',
            field=models.TextField(default='text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deck',
            name='name',
            field=models.CharField(default='name', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.TextField(default='text'),
            preserve_default=False,
        ),
    ]
