# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0005_auto_20160529_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='active_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='deck.Question'),
        ),
    ]
