# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('deck', '0006_class_active_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alternative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deck.Alternative')),
                ('in_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deck.Class')),
            ],
        ),
    ]
